FROM golang:1.9
LABEL cibuild.context-stream=tar

RUN go get -v github.com/Masterminds/glide
WORKDIR /go/src/github.com/github/kube-service-exporter
COPY . .
RUN make
CMD tar -cf - Dockerfile.release bin/kube-service-exporter
