apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: kube-service-exporter
  labels:
    k8s-app: kube-service-exporter
spec:
  selector:
    matchLabels:
      k8s-app: kube-service-exporter
  template:
    metadata:
      labels:
        k8s-app: kube-service-exporter
    spec:
      serviceAccountName: kube-service-exporter
      containers:
      - name: kube-service-exporter
        image: github/kube-service-exporter:ceb932bbe250bd146efce5cda90ff40df566b90f
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          timeoutSeconds: 5
          httpGet:
            path: /healthz
            port: http
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "5"]
        env:
        - name: KSE_CONSUL_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: KSE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KSE_SERVICES_ENABLED
          value: "true"
        - name: KSE_CLUSTER_ID
          value: $CLUSTER_ID
