#!/usr/bin/env bash

if [ "$(uname)" = "Darwin" ]; then
  brew bundle
  [ -x $(which envsubst) ] || brew link --force gettext
fi

# install kind (Kubernetes IN Docker)
[ -x $(which kind) ] || go get -u sigs.k8s.io/kind
